package com.tridhya.chatsta.enum.chat

enum class MessageType {
    NOTAPPLICABLE, TEXT, MEDIA, EMOJI, SOUND_EMOJI, IMAGE, AUDIO, VIDEO, FILE, CREATED_GROUP, DELETED_GROUP, ADDED_MEMBERS, DELETED_MEMBERS, LEFT_GROUP, SCREEN_SHOT
}